language: python
python:
  - "3.6" # default 
os:
  - linux
addons:
  apt:
    packages:
      - cmake
install:
  - cd ibm-llvm/crucible
  - ./compile_llvm
  - cd fusion
  - mkdir build
  - cd build
  - source ../../env.sh
  - cmake ../
  - make
