arch: amd64
os: linux
dist: focal
language: python
python:
  - "3.6" # default 
addons:
  apt:
    packages:
      - cmake
      - gcc-7

language: python

cache:
  apt: true
  pip: true
  directories:
    - llvm-project
    - graphviz

before_install:
  - sudo apt-get install flex
  - ./compile_llvm_minimal.sh
  - ./compile_graphviz.sh

install:
  - cd fusion
  - mkdir build
  - cd build
  - source ../../env.sh
  - cmake ../
  - make
notifications:
  email: never
