language: python
python:
  - "3.6" # default 
os:
  - linux
dist:
  - bionic
addons:
  apt:
    packages:
      - cmake
install:
  - ./compile_llvm.sh
  - cd fusion
  - mkdir build
  - cd build
  - source ../../env.sh
  - cmake ../
  - make
