dist: bionic
addons:
  apt:
    packages:
      - cmake
      - g++-10
language: python
python:
  - "3.6" # default 
install:
  - ./compile_llvm.sh
  - cd fusion
  - mkdir build
  - cd build
  - source ../../env.sh
  - cmake ../
  - make
